apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: haproxy-ingress-controller
  namespace: ingress
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: haproxy-ingress-controller
        phase: prod
    spec:
      nodeSelector:
        node-role.kubernetes.io/node: ""
      containers:
        - name: haproxy-ingress-controller
          image: quay.io/jcmoraisjr/haproxy-ingress
          args:
          - --default-backend-service=$(POD_NAMESPACE)/default-backend
          - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
          - --configmap=$(POD_NAMESPACE)/haproxy-ingress
          # use downward API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
            - name: stat
              containerPort: 1936
              hostPort: 1936
            - name: health
              containerPort: 10253
              hostPort: 10253
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10253
              scheme: HTTP
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 1
            httpGet:
              path: /healthz
              port: 10253
              scheme: HTTP
      hostNetwork: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
