apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-controller
  namespace: ingress
spec:
  type: ClusterIP
  selector:
    name: haproxy-ingress-controller
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
